### ISSUE TITLE
Zooming on image window with trackpad pans the image

### ISSUE THREAD

**Issue by keastrid** [keastrid/astroimagej#6]
When zooming on an image window, the image will drift up and to the left constantly. This is contrary to scrolling with a mouse wheel, which does not drift the image.

This issue is known to effect windows and mac, and potentially linux.

**Comment by karenacollins** [comment]
Fixed with update 26737cd9ea9e8877451027ce8144644d857ff20f.

**Comment by karenacollins** [comment]
Fixed with update 26737cd9ea9e8877451027ce8144644d857ff20f. Trackpad creates many mouseWheelListener triggers, but with mouse wheel movement set to 0 instead of 1 or -1. The triggers with change = 0 are now filtered out.
